@echo off
:: ============================================
:: Wreckfest Head Tracking - Uninstall
:: ============================================
:: Thin wrapper - uninstall body lives in cameraunlock-core/scripts/uninstall-body.cmd,
:: staged into the release ZIP's shared/ by Copy-SharedBundle. One body covers
:: every loader; FRAMEWORK_TYPE dispatches, and it MUST match what install
:: wrote to the state file.
::
:: Source of truth for everything below the CONFIG BLOCK:
:: cameraunlock-core/scripts/templates/uninstall-wrapper.cmd. Copy this file to
:: <mod>/scripts/uninstall.cmd, fill in the CONFIG BLOCK, change nothing else.
:: scripts/conformance.ps1 checks that nothing else changed.
:: ============================================

:: --- CONFIG BLOCK ---
set "GAME_ID=wreckfest"
set "MOD_DISPLAY_NAME=Wreckfest Head Tracking"
set "MOD_DLLS=WreckfestHeadTracking.asi"
set "MOD_INTERNAL_NAME=WreckfestHeadTracking"
set "STATE_FILE=.headtracking-state.json"
:: BepInEx | MelonLoader | MonoCecil | ASILoader | REFramework | UE4SS | xNVSE
:: | None
set "FRAMEWORK_TYPE=ASILoader"
:: DLL names shipped by older versions of this mod, removed too so an upgrade
:: does not leave a second copy for the loader to bind. Empty: this mod has had
:: no prior release, so there is no earlier filename in the wild.
set "LEGACY_DLLS="
:: BepInEx: subfolder under BepInEx\plugins\ the DLLs were deployed into.
set "PLUGIN_SUBFOLDER="
:: Files install.cmd seeded write-if-absent. MUST list the same names as
:: install.cmd's MOD_SEED_FILES, or an uninstall leaves the mod's config behind.
set "MOD_SEED_FILES="
:: Config and log files the mod writes at runtime, removed from wherever the
:: DLLs were deployed. HeadTracking.ini is generated by config.cpp on first run;
:: HeadTracking.log is rotated to HeadTracking.prev.log on each launch.
set "MOD_LEFTOVERS=HeadTracking.ini HeadTracking.log HeadTracking.prev.log"
:: Files to remove from the game root. Only needed by a mod deployed BELOW the
:: root (see ASI_SUBDIR) that still resolves its config and log from the exe's
:: own directory. This mod deploys at the root, so MOD_LEFTOVERS already covers it.
set "ROOT_EXTRAS="

:: --- Loader-specific config (leave the ones that don't apply blank) ---
:: MonoCecil: used to find + restore the original Assembly-CSharp.dll.
set "MANAGED_SUBFOLDER="
set "ASSEMBLY_DLL="
:: MonoCecil: marker the patcher injects; guards against capturing/restoring a
:: patched Assembly-CSharp.dll as the pristine .original backup.
set "PATCH_MARKER="
:: MonoCecil: extra files to also remove from MANAGED_SUBFOLDER (config/log
:: files left behind by the mod itself).
set "MANAGED_EXTRAS="
:: ASILoader: filename the ASI DLL was renamed to. MUST match install.cmd.
set "ASI_LOADER_NAME=version.dll"
:: ASILoader: subdirectory below the exe directory the payload went into. MUST
:: match install.cmd's value, or uninstall looks in the wrong folder.
set "ASI_SUBDIR="
:: UE4SS: path under GAME_PATH holding the shipping exe. MUST match
:: install.cmd's value.
set "UE4_BINARIES_RELDIR="
:: --- END CONFIG BLOCK ---

:: Pin delayed expansion off before `%*` is expanded on the `call` below.
:: Under `cmd /V:ON`, or with DelayedExpansion=1 in
:: HKCU\Software\Microsoft\Command Processor, cmd.exe eats a `!` out of the
:: expanded line, and a real game path like C:\Games\Oh! My Game reaches the
:: body already mangled. The body pins expansion off at its own outer scope
:: too, but that is one `call` too late to save the argument it was handed.
setlocal disabledelayedexpansion

set "WRAPPER_DIR=%~dp0"
set "_BODY=%WRAPPER_DIR%shared\uninstall-body.cmd"
if not exist "%_BODY%" set "_BODY=%WRAPPER_DIR%..\cameraunlock-core\scripts\uninstall-body.cmd"
if not exist "%_BODY%" (
    echo ERROR: uninstall-body.cmd not found in shared\ or ..\cameraunlock-core\scripts\.
    echo If this is a release ZIP, re-download it from GitHub ^(corrupt installer^).
    echo If this is the dev tree, run: git submodule update --init --recursive
    exit /b 1
)
call "%_BODY%" %*
exit /b %errorlevel%
